// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/DKV_DB.proto

package dkvdb_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Id            uint64                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proto_DKV_DB_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DKV_DB_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_DKV_DB_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxRequest) Reset() {
	*x = TxRequest{}
	mi := &file_proto_DKV_DB_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRequest) ProtoMessage() {}

func (x *TxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DKV_DB_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRequest.ProtoReflect.Descriptor instead.
func (*TxRequest) Descriptor() ([]byte, []int) {
	return file_proto_DKV_DB_proto_rawDescGZIP(), []int{1}
}

func (x *TxRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_DKV_DB_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DKV_DB_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_DKV_DB_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_DKV_DB_proto protoreflect.FileDescriptor

const file_proto_DKV_DB_proto_rawDesc = "" +
	"\n" +
	"\x12proto/DKV_DB.proto\x12\rdkvdb_service\"D\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\"\x1b\n" +
	"\tTxRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"<\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbc\x01\n" +
	"\fDKVDBService\x127\n" +
	"\x03Set\x12\x19.dkvdb_service.SetRequest\x1a\x15.dkvdb_service.Status\x129\n" +
	"\x06Commit\x12\x18.dkvdb_service.TxRequest\x1a\x15.dkvdb_service.Status\x128\n" +
	"\x05Abort\x12\x18.dkvdb_service.TxRequest\x1a\x15.dkvdb_service.StatusB5Z3github.com/anormalprgrmr/DKV_DB/proto;dkvdb_serviceb\x06proto3"

var (
	file_proto_DKV_DB_proto_rawDescOnce sync.Once
	file_proto_DKV_DB_proto_rawDescData []byte
)

func file_proto_DKV_DB_proto_rawDescGZIP() []byte {
	file_proto_DKV_DB_proto_rawDescOnce.Do(func() {
		file_proto_DKV_DB_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_DKV_DB_proto_rawDesc), len(file_proto_DKV_DB_proto_rawDesc)))
	})
	return file_proto_DKV_DB_proto_rawDescData
}

var file_proto_DKV_DB_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_DKV_DB_proto_goTypes = []any{
	(*SetRequest)(nil), // 0: dkvdb_service.SetRequest
	(*TxRequest)(nil),  // 1: dkvdb_service.TxRequest
	(*Status)(nil),     // 2: dkvdb_service.Status
}
var file_proto_DKV_DB_proto_depIdxs = []int32{
	0, // 0: dkvdb_service.DKVDBService.Set:input_type -> dkvdb_service.SetRequest
	1, // 1: dkvdb_service.DKVDBService.Commit:input_type -> dkvdb_service.TxRequest
	1, // 2: dkvdb_service.DKVDBService.Abort:input_type -> dkvdb_service.TxRequest
	2, // 3: dkvdb_service.DKVDBService.Set:output_type -> dkvdb_service.Status
	2, // 4: dkvdb_service.DKVDBService.Commit:output_type -> dkvdb_service.Status
	2, // 5: dkvdb_service.DKVDBService.Abort:output_type -> dkvdb_service.Status
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_DKV_DB_proto_init() }
func file_proto_DKV_DB_proto_init() {
	if File_proto_DKV_DB_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_DKV_DB_proto_rawDesc), len(file_proto_DKV_DB_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_DKV_DB_proto_goTypes,
		DependencyIndexes: file_proto_DKV_DB_proto_depIdxs,
		MessageInfos:      file_proto_DKV_DB_proto_msgTypes,
	}.Build()
	File_proto_DKV_DB_proto = out.File
	file_proto_DKV_DB_proto_goTypes = nil
	file_proto_DKV_DB_proto_depIdxs = nil
}
