// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/DKV_DB.proto

package dkvdb_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DKVDBService_Set_FullMethodName    = "/dkvdb_service.DKVDBService/Set"
	DKVDBService_Commit_FullMethodName = "/dkvdb_service.DKVDBService/Commit"
	DKVDBService_Abort_FullMethodName  = "/dkvdb_service.DKVDBService/Abort"
)

// DKVDBServiceClient is the client API for DKVDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DKVDBServiceClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Status, error)
	Commit(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*Status, error)
	Abort(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*Status, error)
}

type dKVDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDKVDBServiceClient(cc grpc.ClientConnInterface) DKVDBServiceClient {
	return &dKVDBServiceClient{cc}
}

func (c *dKVDBServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, DKVDBService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVDBServiceClient) Commit(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, DKVDBService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVDBServiceClient) Abort(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, DKVDBService_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DKVDBServiceServer is the server API for DKVDBService service.
// All implementations must embed UnimplementedDKVDBServiceServer
// for forward compatibility.
type DKVDBServiceServer interface {
	Set(context.Context, *SetRequest) (*Status, error)
	Commit(context.Context, *TxRequest) (*Status, error)
	Abort(context.Context, *TxRequest) (*Status, error)
	mustEmbedUnimplementedDKVDBServiceServer()
}

// UnimplementedDKVDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDKVDBServiceServer struct{}

func (UnimplementedDKVDBServiceServer) Set(context.Context, *SetRequest) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedDKVDBServiceServer) Commit(context.Context, *TxRequest) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedDKVDBServiceServer) Abort(context.Context, *TxRequest) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedDKVDBServiceServer) mustEmbedUnimplementedDKVDBServiceServer() {}
func (UnimplementedDKVDBServiceServer) testEmbeddedByValue()                      {}

// UnsafeDKVDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DKVDBServiceServer will
// result in compilation errors.
type UnsafeDKVDBServiceServer interface {
	mustEmbedUnimplementedDKVDBServiceServer()
}

func RegisterDKVDBServiceServer(s grpc.ServiceRegistrar, srv DKVDBServiceServer) {
	// If the following call panics, it indicates UnimplementedDKVDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DKVDBService_ServiceDesc, srv)
}

func _DKVDBService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVDBServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DKVDBService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVDBServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKVDBService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVDBServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DKVDBService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVDBServiceServer).Commit(ctx, req.(*TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKVDBService_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVDBServiceServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DKVDBService_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVDBServiceServer).Abort(ctx, req.(*TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DKVDBService_ServiceDesc is the grpc.ServiceDesc for DKVDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DKVDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dkvdb_service.DKVDBService",
	HandlerType: (*DKVDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _DKVDBService_Set_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _DKVDBService_Commit_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _DKVDBService_Abort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/DKV_DB.proto",
}
